const products=[
{id:'run-x1',name:'ران‌اکس X1',image:shoeImage('#d9f0e7','#0d5b4e'),cashPrice:2890000,creditPrice:760000,sizes:[40,41,42,43,44],stock:12,description:'سبک و سریع برای دویدن روزانه',badge:'پرفروش'},
{id:'air-motion',name:'ایر موشن پرو',image:shoeImage('#e8edf8','#394e91'),cashPrice:3450000,creditPrice:910000,sizes:[41,42,43,44,45],stock:7,description:'کفی نرم با جذب ضربه عالی',badge:'جدید'},
{id:'street-flex',name:'استریت فلکس',image:shoeImage('#f5e9d9','#b96b32'),cashPrice:2190000,creditPrice:580000,sizes:[40,41,42,43],stock:4,description:'انتخابی راحت برای استفاده روزمره',badge:'محدود'},
{id:'pace-elite',name:'پیس الیت',image:shoeImage('#eee3f2','#74418c'),cashPrice:4190000,creditPrice:1100000,sizes:[42,43,44,45],stock:0,description:'ساختار حرفه‌ای برای تمرین جدی',badge:'ویژه'},
{id:'trail-grip',name:'تریل گریپ',image:shoeImage('#e2eee1','#487b43'),cashPrice:3180000,creditPrice:835000,sizes:[40,42,43,44],stock:9,description:'چسبندگی مطمئن در مسیرهای سخت',badge:'ضدآب'},
{id:'urban-lite',name:'اوربان لایت',image:shoeImage('#f0e5e5','#9c3d4c'),cashPrice:2490000,creditPrice:655000,sizes:[41,42,43,44,45],stock:2,description:'مینیمال، سبک و مناسب شهر',badge:'آخرین موجودی'}
];
let cart=loadCart();let selectedProduct=null;let selectedSize=null;let modalQty=1;let purchaseType='cash';
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('fa-IR').format(n)+' تومان';
function shoeImage(bg,accent){const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400"><rect width="600" height="400" fill="${bg}"/><circle cx="490" cy="90" r="130" fill="#ffffff55"/><path d="M95 244c47-5 78-27 112-83l38-62c12-20 28-19 45-5l66 59c29 26 61 41 118 54l55 12c24 5 37 17 35 35-3 25-34 40-72 40H118c-47 0-63-38-23-50z" fill="${accent}"/><path d="M115 253h348c30 0 68 5 79 18-10 15-34 23-76 23H119c-38 0-47-28-4-41z" fill="#fff"/><path d="M245 115l70 67m-92-36 65 66m-88-36 53 57" stroke="#fff" stroke-width="13" stroke-linecap="round" opacity=".8"/><text x="35" y=" fifty" fill="${accent}" font-family="Arial" font-size="20" font-weight="bold">GAMENO</text></svg>`.replace('y=" fifty"','y="50"');return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function loadCart(){try{return JSON.parse(localStorage.getItem('gameno-cart'))||[]}catch{return[]}}function saveCart(){localStorage.setItem('gameno-cart',JSON.stringify(cart))}
function stockInfo(p){if(!p.stock)return['ناموجود','out'];if(p.stock<=4)return[`تنها ${p.stock} عدد باقی مانده`,'limited'];return['موجود در انبار','available']}
function renderProducts(){const query=$('#searchInput').value.trim().toLowerCase();const size=$('#sizeFilter').value;const sort=$('#sortFilter').value;let list=products.filter(p=>(p.name.toLowerCase().includes(query)||p.description.includes(query))&&(size==='all'||p.sizes.includes(Number(size))));if(sort==='low')list.sort((a,b)=>a.cashPrice-b.cashPrice);if(sort==='high')list.sort((a,b)=>b.cashPrice-a.cashPrice);if(sort==='stock')list.sort((a,b)=>b.stock-a.stock);$('#resultText').textContent=`${new Intl.NumberFormat('fa-IR').format(list.length)} محصول برای شما`;$('#productGrid').innerHTML=list.map(card).join('');$('#emptyProducts').classList.toggle('hidden',!!list.length)}
function card(p){const [status,cls]=stockInfo(p);return `<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}"><span class="badge">${p.badge}</span></div><div class="product-info"><h3>${p.name}</h3><p class="description">${p.description}</p><div class="price-line"><div class="price"><strong>${money(p.cashPrice)}</strong><small>اعتباری: ماهانه ${money(p.creditPrice)}</small></div><span class="stock ${cls}">${status}</span></div><div class="card-bottom"><span class="sizes">سایزهای ${p.sizes.join('، ')}</span><button class="details-button" data-product="${p.id}" ${!p.stock?'disabled':''}>انتخاب سایز</button></div></div></article>`}
function openModal(id){selectedProduct=products.find(p=>p.id===id);selectedSize=null;modalQty=1;const p=selectedProduct;$('#modalContent').innerHTML=`<div class="modal-product"><img src="${p.image}" alt="${p.name}"><div><span class="eyebrow">${p.badge}</span><h2 id="modalTitle">${p.name}</h2><p>${p.description}</p><div class="modal-price">${money(p.cashPrice)} <small>نقدی</small></div><div class="option-title">سایز را انتخاب کنید</div><div class="size-list">${p.sizes.map(s=>`<button class="size-option" data-size="${s}" type="button">${s}</button>`).join('')}</div><div class="option-title">تعداد</div><div class="quantity"><button id="modalMinus" type="button">−</button><strong id="modalQty">۱</strong><button id="modalPlus" type="button">+</button><span class="stock available">حداکثر ${p.stock} عدد</span></div><button class="primary-button add-button" id="addToCartButton" type="button">افزودن به سبد خرید</button></div></div>`;$('#productModal').classList.remove('hidden')}
function addToCart(){if(!selectedSize)return toast('لطفاً یک سایز انتخاب کنید');const p=selectedProduct;const found=cart.find(i=>i.productId===p.id&&i.size===selectedSize);if((found?.qty||0)+modalQty>p.stock)return toast('تعداد انتخابی بیشتر از موجودی انبار است');if(found)found.qty+=modalQty;else cart.push({productId:p.id,size:selectedSize,qty:modalQty});saveCart();renderCart();$('#productModal').classList.add('hidden');openCart();toast('محصول با موفقیت به سبد اضافه شد')}
function renderCart(){const count=cart.reduce((a,i)=>a+i.qty,0);$('#cartCount').textContent=new Intl.NumberFormat('fa-IR').format(count);if(!cart.length){$('#cartItems').innerHTML='<div class="empty-state"><span>🛒</span><h3>سبد خرید خالی است</h3><p>محصول مورد علاقه‌تان را به سبد اضافه کنید.</p></div>';$('#cartFooter').classList.add('hidden');return}$('#cartFooter').classList.remove('hidden');$('#cartItems').innerHTML=cart.map((item,index)=>{const p=products.find(x=>x.id===item.productId);const unit=purchaseType==='cash'?p.cashPrice:p.creditPrice;return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h4>${p.name}</h4><p>سایز ${item.size} · ${purchaseType==='cash'?'نقدی':'اعتباری'}</p><span class="item-price">${money(unit)}</span><div class="item-controls"><button data-action="minus" data-index="${index}">−</button><b>${item.qty}</b><button data-action="plus" data-index="${index}">+</button><button class="remove-item" data-action="remove" data-index="${index}" aria-label="حذف">×</button></div></div><strong>${money(unit*item.qty)}</strong></div>`}).join('');updateTotal()}
function updateTotal(){const total=cart.reduce((a,i)=>{const p=products.find(x=>x.id===i.productId);return a+(purchaseType==='cash'?p.cashPrice:p.creditPrice)*i.qty},0);$('#cartTotal').textContent=money(total);$('#creditNote').classList.toggle('hidden',purchaseType!=='credit')}
function openCart(){$('#cartDrawer').classList.add('open');$('#drawerBackdrop').classList.remove('hidden')}function closeCart(){$('#cartDrawer').classList.remove('open');$('#drawerBackdrop').classList.add('hidden')}function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
$('#productGrid').addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(b)openModal(b.dataset.product)});$('#modalContent').addEventListener('click',e=>{if(e.target.matches('[data-size]')){selectedSize=Number(e.target.dataset.size);document.querySelectorAll('.size-option').forEach(b=>b.classList.toggle('selected',Number(b.dataset.size)===selectedSize))}if(e.target.id==='modalMinus')modalQty=Math.max(1,modalQty-1);if(e.target.id==='modalPlus')modalQty=Math.min(selectedProduct.stock,modalQty+1);if(e.target.id==='addToCartButton')addToCart();const q=$('#modalQty');if(q)q.textContent=new Intl.NumberFormat('fa-IR').format(modalQty)});document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',()=>$('#productModal').classList.add('hidden')));$('#openCartButton').onclick=openCart;$('#closeCartButton').onclick=closeCart;$('#drawerBackdrop').onclick=closeCart;$('#searchInput').oninput=renderProducts;$('#sizeFilter').onchange=renderProducts;$('#sortFilter').onchange=renderProducts;document.querySelectorAll('input[name="purchaseType"]').forEach(r=>r.onchange=()=>{purchaseType=r.value;renderCart()});$('#cartItems').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const index=Number(b.dataset.index),item=cart[index],p=products.find(x=>x.id===item.productId);if(b.dataset.action==='remove')cart.splice(index,1);if(b.dataset.action==='minus'){item.qty--;if(item.qty<1)cart.splice(index,1)}if(b.dataset.action==='plus'){if(item.qty>=p.stock)return toast('بیشتر از موجودی انبار نمی‌توان افزود');item.qty++}saveCart();renderCart()});$('#checkoutButton').onclick=()=>toast('ثبت سفارش در نسخه نمایشی فعال نیست');renderProducts();renderCart();