const products=[
{id:'a1',brand:'آدیداس',name:'Ultraboost Light',price:4850000,color:'مشکی و سفید',description:'کفشی سبک و پاسخ‌گو برای دویدن‌های روزانه و تمرین‌های طولانی.',sizes:{40:3,41:5,42:4,43:2}},
{id:'a2',brand:'آدیداس',name:'Runfalcon 3',price:2750000,color:'سرمه‌ای',description:'انتخابی راحت و اقتصادی برای فعالیت‌های روزمره و ورزشی.',sizes:{40:4,41:2,42:6,44:3}},
{id:'a3',brand:'آدیداس',name:'Duramo SL',price:3200000,color:'طوسی',description:'با کفی نرم و تهویه مناسب، مناسب تمرین و پیاده‌روی.',sizes:{41:3,42:5,43:4,44:2}},
{id:'n1',brand:'نایک',name:'Air Zoom Pegasus',price:5200000,color:'سفید و آبی',description:'کفشی پرانرژی با بالشتک‌گذاری عالی برای دویدن سریع.',sizes:{40:2,41:4,42:5,43:3}},
{id:'n2',brand:'نایک',name:'Revolution 7',price:2950000,color:'مشکی',description:'طراحی مینیمال و راحتی قابل اعتماد برای استفاده روزانه.',sizes:{39:3,40:5,42:2,43:4}},
{id:'n3',brand:'نایک',name:'Downshifter 12',price:3450000,color:'سبز زیتونی',description:'انعطاف‌پذیر و بادوام برای تمرین‌های سبک و متوسط.',sizes:{40:1,41:3,43:5,44:2}}
];
const state={cart:loadCart(),query:'',brand:'all',size:'all',sort:'featured',selectedSize:null,selectedProduct:null};
const fa=n=>new Intl.NumberFormat('fa-IR').format(n); const toman=n=>`${fa(n)} تومان`;
function loadCart(){try{return JSON.parse(localStorage.getItem('tandar-cart'))||[]}catch{return[]}}
function saveCart(){try{localStorage.setItem('tandar-cart',JSON.stringify(state.cart))}catch{}}
function stock(p){return Object.values(p.sizes).reduce((a,b)=>a+b,0)}
function image(){return '<span class="shoe">👟</span>'}
function filtered(){let list=products.filter(p=>(p.name+' '+p.brand).includes(state.query)&&(state.brand==='all'||p.brand===state.brand)&&(state.size==='all'||p.sizes[state.size]));if(state.sort==='priceAsc')list.sort((a,b)=>a.price-b.price);if(state.sort==='priceDesc')list.sort((a,b)=>b.price-a.price);if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));if(state.sort==='stock')list.sort((a,b)=>stock(b)-stock(a));return list}
function renderProducts(){const grid=document.querySelector('#productsGrid');if(!grid)return;const list=filtered();grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image">${image()}<span class="badge">${p.brand}</span></div><div class="product-info"><span class="brand-name">${p.color}</span><h3>${p.name}</h3><div class="product-bottom"><div><div class="price">${toman(p.price)} <small>/ جفت</small></div><span class="stock ${stock(p)<7?'low':''}">${fa(stock(p))} جفت موجود</span></div><button class="card-button" data-product="${p.id}">انتخاب سایز</button></div></div></article>`).join('');document.querySelector('#emptyProducts').classList.toggle('hidden',list.length>0)}
function renderFilters(){const brands=[...new Set(products.map(p=>p.brand))];document.querySelector('#brandFilter').innerHTML='<option value="all">همه برندها</option>'+brands.map(x=>`<option>${x}</option>`).join('');const sizes=[...new Set(products.flatMap(p=>Object.keys(p.sizes)))].sort();document.querySelector('#sizeFilter').innerHTML='<option value="all">همه سایزها</option>'+sizes.map(x=>`<option value="${x}">سایز ${x}</option>`).join('')}
function openProduct(id){const p=products.find(x=>x.id===id);state.selectedProduct=p;state.selectedSize=Object.keys(p.sizes)[0];document.querySelector('#modalContent').innerHTML=`<div class="detail-layout"><div class="detail-image">${image()}</div><div class="detail-info"><span class="brand-name">${p.brand} | ${p.color}</span><h2 id="modalTitle">${p.name}</h2><p class="description">${p.description}</p><div class="price">${toman(p.price)}</div><p><b>انتخاب سایز:</b></p><div class="size-list">${Object.entries(p.sizes).map(([s,n])=>`<button class="${s==state.selectedSize?'selected':''}" data-size="${s}" ${n<1?'disabled':''}>${s}<small> (${fa(n)})</small></button>`).join('')}</div><div class="quantity"><b>تعداد:</b><button id="qtyMinus" type="button">−</button><span id="qtyValue">۱</span><button id="qtyPlus" type="button">+</button></div><button id="addToCart" class="primary-button full-width" type="button">افزودن به سبد</button></div></div>`;document.querySelector('#productModal').classList.remove('hidden');bindDetail()}
function bindDetail(){let qty=1;const p=state.selectedProduct;const update=()=>document.querySelector('#qtyValue').textContent=fa(qty);document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{state.selectedSize=b.dataset.size;document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('selected',x===b));qty=1;update()});document.querySelector('#qtyMinus').onclick=()=>{qty=Math.max(1,qty-1);update()};document.querySelector('#qtyPlus').onclick=()=>{if(qty<p.sizes[state.selectedSize])qty++;else toast('تعداد انتخابی از موجودی بیشتر است');update()};document.querySelector('#addToCart').onclick=()=>{addToCart(p.id,state.selectedSize,qty);closeProduct()}}
function addToCart(productId,size,quantity=1){const p=products.find(x=>x.id===productId), existing=state.cart.find(x=>x.productId===productId&&String(x.size)===String(size)), next=(existing?existing.quantity:0)+quantity;if(next>p.sizes[size])return toast('موجودی این سایز کافی نیست');if(existing)existing.quantity=next;else state.cart.push({productId,size:String(size),quantity});saveCart();renderCart();toast('محصول به سبد خرید اضافه شد')}
function renderCart(){const total=state.cart.reduce((sum,i)=>sum+products.find(p=>p.id===i.productId).price*i.quantity,0),count=state.cart.reduce((s,i)=>s+i.quantity,0);document.querySelector('#cartCount').textContent=fa(count);document.querySelector('#cartTotal').textContent=toman(total);document.querySelector('#cartItems').innerHTML=state.cart.map((i,index)=>{const p=products.find(x=>x.id===i.productId);return `<div class="cart-line"><div class="cart-thumb">👟</div><div class="cart-line-info"><strong>${p.name}</strong><small>${p.brand} | سایز ${i.size} | ${toman(p.price)}</small><div class="line-actions"><button data-action="minus" data-index="${index}">−</button><b>${fa(i.quantity)}</b><button data-action="plus" data-index="${index}">+</button><button class="remove" data-action="remove" data-index="${index}">حذف</button></div></div></div>`}).join('');const empty=!state.cart.length;document.querySelector('#cartEmpty').classList.toggle('hidden',!empty);document.querySelector('#cartFooter').classList.toggle('hidden',empty)}
function changeCart(index,action){const i=state.cart[index],p=products.find(x=>x.id===i.productId);if(action==='remove')state.cart.splice(index,1);else if(action==='minus')i.quantity--;else if(i.quantity<p.sizes[i.size])i.quantity++;else return toast('بیشتر از موجودی نمی‌توانید انتخاب کنید');if(i&&i.quantity<1)state.cart.splice(index,1);saveCart();renderCart()}
function closeProduct(){document.querySelector('#productModal').classList.add('hidden')};function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function openCart(){document.querySelector('#cartDrawer').classList.add('open');document.querySelector('#cartDrawer').setAttribute('aria-hidden','false');document.querySelector('#overlay').classList.remove('hidden')};function closeCart(){document.querySelector('#cartDrawer').classList.remove('open');document.querySelector('#cartDrawer').setAttribute('aria-hidden','true');document.querySelector('#overlay').classList.add('hidden')}
if(typeof document!=='undefined'){document.addEventListener('DOMContentLoaded',()=>{renderFilters();renderProducts();renderCart();document.querySelector('#searchInput').oninput=e=>{state.query=e.target.value.trim();renderProducts()};document.querySelector('#brandFilter').onchange=e=>{state.brand=e.target.value;renderProducts()};document.querySelector('#sizeFilter').onchange=e=>{state.size=e.target.value;renderProducts()};document.querySelector('#sortSelect').onchange=e=>{state.sort=e.target.value;renderProducts()};document.querySelector('#productsGrid').onclick=e=>{const b=e.target.closest('[data-product]');if(b)openProduct(b.dataset.product)};document.querySelector('#cartItems').onclick=e=>{const b=e.target.closest('[data-action]');if(b)changeCart(+b.dataset.index,b.dataset.action)};document.querySelector('#cartButton').onclick=openCart;document.querySelector('#closeCart').onclick=closeCart;document.querySelector('#overlay').onclick=closeCart;document.querySelector('#closeModal').onclick=closeProduct;document.querySelector('#checkoutButton').onclick=()=>{if(state.cart.length){closeCart();document.querySelector('#checkoutModal').classList.remove('hidden')}};document.querySelector('#closeCheckout').onclick=()=>document.querySelector('#checkoutModal').classList.add('hidden');document.querySelector('#checkoutForm').onsubmit=e=>{e.preventDefault();state.cart=[];saveCart();renderCart();document.querySelector('#checkoutModal').classList.add('hidden');toast('سفارش نمایشی شما با موفقیت ثبت شد');e.target.reset()};document.querySelectorAll('input[name="payment"]').forEach(x=>x.onchange=()=>{const total=state.cart.reduce((s,i)=>s+products.find(p=>p.id===i.productId).price*i.quantity,0);document.querySelector('#installmentText').textContent=`هر قسط ${toman(Math.ceil(total/4))} در ۴ قسط مساوی`})})}
if(typeof module!=='undefined')module.exports={products,filtered,stock,addToCart,formatPrice:toman};