export const products = [
  {id:'a1',name:'آدیداس اولترا بوست لایت',brand:'آدیداس',price:4850000,sizes:[40,41,42,43,44],stock:7,color:'#dce7bf',rating:4.9,created:4,description:'کفشی سبک و پاسخ‌گو برای دویدن‌های روزانه با کفی نرم و تنفس‌پذیر.'},
  {id:'a2',name:'آدیداس سوپرنوا استراید',brand:'آدیداس',price:3620000,sizes:[39,40,41,42,43],stock:3,color:'#ded9cf',rating:4.7,created:3,description:'انتخابی راحت برای تمرین و استفاده روزمره با پشتیبانی مناسب.'},
  {id:'n1',name:'نایک ایر زوم پگاسوس',brand:'نایک',price:4190000,sizes:[40,41,42,43,44,45],stock:9,color:'#d7e2e5',rating:4.8,created:5,description:'کفش محبوب دویدن با بالشتک‌گذاری نرم و طراحی کلاسیک نایک.'},
  {id:'n2',name:'نایک رنینگ اینتراکت',brand:'نایک',price:2980000,sizes:[41,42,43],stock:0,color:'#ead9d0',rating:4.5,created:2,description:'کفشی روزمره و سبک برای حرکت راحت در تمام روز.'},
  {id:'n3',name:'نایک ایر فورس اسپرت',brand:'نایک',price:3870000,sizes:[40,41,42,44],stock:5,color:'#e2dfed',rating:4.6,created:1,description:'ترکیبی از ظاهر شهری و راحتی ورزشی برای استایل روزانه.'},
  {id:'a3',name:'آدیداس ران فالکن',brand:'آدیداس',price:2450000,sizes:[39,40,42,43],stock:12,color:'#e0e0d2',rating:4.4,created:6,description:'کفش اقتصادی و کاربردی برای شروع تمرین‌های ورزشی.'}
];
export const toman = n => new Intl.NumberFormat('fa-IR').format(n) + ' تومان';
export function findProduct(id){return products.find(p=>p.id===id)}
export function cleanCart(cart){return cart.filter(i=>{const p=findProduct(i.id);return p&&p.sizes.includes(Number(i.size))&&i.qty>0&&p.stock>0}).map(i=>({...i,size:Number(i.size),qty:Math.min(i.qty,findProduct(i.id).stock)}))}
export function addToCart(cart,id,size,qty=1){const p=findProduct(id);if(!p||!size||!p.sizes.includes(Number(size)))throw Error('لطفاً سایز را انتخاب کنید.');if(p.stock<1)throw Error('این محصول ناموجود است.');const next=cart.map(x=>({...x})), old=next.find(x=>x.id===id&&Number(x.size)===Number(size));if(old){if(old.qty+qty>p.stock)throw Error('تعداد انتخابی بیشتر از موجودی انبار است.');old.qty+=qty}else{if(qty>p.stock)throw Error('تعداد انتخابی بیشتر از موجودی انبار است.');next.push({id,size:Number(size),qty})}return next}
export function changeQty(cart,index,delta){const next=cart.map(x=>({...x})),i=next[index],p=i&&findProduct(i.id);if(!i||!p)return next;if(i.qty+delta<1)return next.filter((_,n)=>n!==index);i.qty=Math.min(p.stock,i.qty+delta);return next}
export function cartTotal(cart){return cart.reduce((sum,i)=>sum+(findProduct(i.id)?.price||0)*i.qty,0)}
export function creditInstallment(total){return Math.ceil(total/4)}

if(typeof document!=='undefined'){
  let cart=cleanCart(JSON.parse(localStorage.getItem('kicks-cart')||'[]')), brand='all', query='', sort='popular';
  const $=s=>document.querySelector(s), grid=$('#product-grid'), toast=$('#toast');
  const save=()=>{localStorage.setItem('kicks-cart',JSON.stringify(cart));renderCart()};
  const notify=msg=>{toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)};
  const filtered=()=>products.filter(p=>(brand==='all'||p.brand===brand)&&(`${p.name} ${p.brand}`.includes(query))).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='newest'?b.created-a.created:b.rating-a.rating);
  function renderProducts(){const list=filtered();$('#empty-products').classList.toggle('hidden',list.length>0);grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-visual" style="--color:${p.color}"><span class="brand-tag">${p.brand}</span></div><div class="stock ${p.stock?'':'out'}">${p.stock?'موجود در انبار · '+p.stock+' عدد':'ناموجود'}</div><h3>${p.name}</h3><div class="product-meta">${p.color==='x'?'':'رنگ منتخب'} · امتیاز ${p.rating}</div><div class="card-bottom"><span class="price">${toman(p.price)} <small>/ جفت</small></span><button class="add-button" data-detail="${p.id}" ${p.stock?'':'disabled'}>${p.stock?'انتخاب سایز':'تمام شد'}</button></div></article>`).join('');}
  function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0),total=cartTotal(cart);$('#cart-count').textContent=count.toLocaleString('fa-IR');$('#cart-total').textContent=toman(total);$('#cart-items').innerHTML=cart.length?cart.map((i,n)=>{const p=findProduct(i.id);return `<div class="cart-item"><div class="mini-visual"></div><div><h4>${p.name}</h4><small>سایز ${i.size} · ${toman(p.price)}</small><div class="quantity"><button data-change="${n}" data-delta="-1">−</button><b>${i.qty}</b><button data-change="${n}" data-delta="1">+</button></div><button class="remove" data-remove="${n}">حذف</button></div><strong>${toman(p.price*i.qty)}</strong></div>`}).join(''):'<p class="empty">سبد خرید شما خالی است.</p>';const credit=$('#installment');credit.textContent=`هر قسط: ${toman(creditInstallment(total))}`;credit.classList.toggle('hidden',$('input[name=payment]:checked')?.value!=='credit'||!total)}
  function openCart(){renderCart();$('#cart-drawer').classList.add('open');$('#cart-drawer').setAttribute('aria-hidden','false');$('#backdrop').classList.remove('hidden')};function closeCart(){$('#cart-drawer').classList.remove('open');$('#backdrop').classList.add('hidden')}
  function openDetail(id){const p=findProduct(id),d=$('#product-dialog');d.dataset.id=id;d.innerHTML=`<button class="close dialog-close" id="close-dialog" type="button" aria-label="بستن">×</button><div class="detail"><div class="product-visual" style="--color:${p.color}"></div><p class="eyebrow">${p.brand}</p><h2>${p.name}</h2><p class="product-meta">${p.description}</p><div class="detail-row"><span>انتخاب سایز:</span><div class="size-list">${p.sizes.map(s=>`<button data-size="${s}" type="button">${s}</button>`).join('')}</div></div><div class="detail-row"><span>تعداد (موجودی: ${p.stock})</span><input id="detail-qty" type="number" value="1" min="1" max="${p.stock||1}" ${p.stock?'':'disabled'}></div><button class="add-button" id="detail-add" ${p.stock?'':'disabled'}>${p.stock?'افزودن به سبد خرید':'ناموجود'}</button></div>`;d.showModal();d.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{d.querySelectorAll('[data-size]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});$('#detail-add').onclick=()=>{const size=d.querySelector('.selected')?.dataset.size;try{cart=addToCart(cart,id,size,Number($('#detail-qty').value));save();d.close();notify('محصول به سبد خرید اضافه شد.')}catch(e){notify(e.message)}};$('#close-dialog').onclick=()=>d.close()}
  grid.addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b)openDetail(b.dataset.detail)});$('#search').oninput=e=>{query=e.target.value.trim();renderProducts()};$('#sort').onchange=e=>{sort=e.target.value;renderProducts()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');brand=b.dataset.brand;renderProducts()});$('#open-cart').onclick=openCart;$('#close-cart').onclick=closeCart;$('#backdrop').onclick=closeCart;$('#cart-items').onclick=e=>{const c=e.target.closest('[data-change]'),r=e.target.closest('[data-remove]');if(c){cart=changeQty(cart,Number(c.dataset.change),Number(c.dataset.delta));save()}if(r){cart.splice(Number(r.dataset.remove),1);save();notify('آیتم حذف شد')}};document.querySelectorAll('input[name=payment]').forEach(x=>x.onchange=renderCart);$('#checkout').onclick=()=>{if(!cart.length)return notify('سبد خرید خالی است.');cart=[];save();closeCart();notify('سفارش نمایشی شما با موفقیت ثبت شد.');};renderProducts();renderCart();
}
