const PRODUCTS=[
{id:'a1',brand:'آدیداس',name:'Ultraboost Light',price:4850000,description:'کفش سبک و پرانرژی برای دویدن روزانه.',emoji:'👟',stockBySize:{40:2,41:4,42:3,43:1}},
{id:'a2',brand:'آدیداس',name:'Adizero SL',price:3650000,description:'طراحی سریع با تهویه مناسب و کفی راحت.',emoji:'👟',stockBySize:{41:3,42:5,43:2,44:1}},
{id:'a3',brand:'آدیداس',name:'Forum Low Sport',price:2980000,description:'انتخابی جذاب برای استایل روزمره و ورزشی.',emoji:'👟',stockBySize:{40:1,41:2,42:2,44:3}},
{id:'n1',brand:'نایک',name:'Air Zoom Pegasus',price:4250000,description:'کفش دویدن محبوب با ضربه‌گیری نرم.',emoji:'👟',stockBySize:{40:2,41:3,42:4,43:2}},
{id:'n2',brand:'نایک',name:'Revolution 7',price:2750000,description:'سبک، اقتصادی و مناسب تمرین‌های روزانه.',emoji:'👟',stockBySize:{39:2,40:4,41:3,42:1}},
{id:'n3',brand:'نایک',name:'Air Max Pulse',price:5100000,description:'ترکیب راحتی مدرن و ظاهر قدرتمند خیابانی.',emoji:'👟',stockBySize:{41:1,42:2,43:3,44:2}}
];
const money=n=>new Intl.NumberFormat('fa-IR').format(Math.round(n))+' تومان';
const fa=n=>new Intl.NumberFormat('fa-IR').format(n);
const productStock=p=>Object.values(p.stockBySize).reduce((a,b)=>a+b,0);
const findProduct=id=>PRODUCTS.find(p=>p.id===id);
function addToCart(cart,productId,size,quantity=1){const p=findProduct(productId),key=productId+'-'+size,sizeKey=String(size),amount=Number(quantity);if(!p||!Object.prototype.hasOwnProperty.call(p.stockBySize,sizeKey)||!Number.isInteger(amount)||amount<1)return{cart,error:'سایز یا تعداد انتخاب‌شده معتبر نیست.'};const item=cart.find(x=>x.key===key),current=item?item.quantity:0;if(current+amount>p.stockBySize[sizeKey])return{cart,error:'تعداد درخواستی از موجودی این سایز بیشتر است.'};if(item)item.quantity+=amount;else cart.push({key,productId,size:Number(size),quantity:amount});return{cart,error:null}}
function changeQuantity(cart,key,delta){const item=cart.find(x=>x.key===key);if(!item)return cart;const p=findProduct(item.productId);if(!p)return cart.filter(x=>x!==item);item.quantity=Math.max(0,Math.min(p.stockBySize[item.size]||0,item.quantity+delta));return cart.filter(x=>x.quantity>0)}
const cartTotal=cart=>cart.reduce((sum,item)=>{const p=findProduct(item.productId);return sum+(p?p.price*item.quantity:0)},0);
const installments=total=>{const part=Math.floor(total/4);return[part,part,part,total-part*3]};
function loadCart(){try{const value=JSON.parse(localStorage.getItem('power-shoe-cart'));return Array.isArray(value)?value:[]}catch{return[]}}
let cart=typeof localStorage==='undefined'?[]:loadCart();
const $=id=>document.getElementById(id);const saveCart=()=>localStorage.setItem('power-shoe-cart',JSON.stringify(cart));
function renderProducts(){const query=$('search').value.trim().toLowerCase(),brand=$('brand-filter').value,sort=$('sort-select').value;let list=PRODUCTS.filter(p=>(!query||(p.name+' '+p.brand).toLowerCase().includes(query))&&(brand==='all'||p.brand===brand));if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='stock-desc')list.sort((a,b)=>productStock(b)-productStock(a));$('result-count').textContent=fa(list.length)+' محصول';$('product-grid').innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-visual" aria-hidden="true">${p.emoji}</div><div class="product-content"><span class="product-brand">${p.brand}</span><h2 class="product-title">${p.name}</h2><p class="description">${p.description}</p><div class="price">${money(p.price)}</div><div class="stock ${productStock(p)?'':'out'}">${productStock(p)?'موجودی: '+fa(productStock(p))+' عدد':'ناموجود'}</div><div class="card-actions"><button class="secondary-button detail-btn" data-id="${p.id}" type="button">جزئیات</button><button class="primary-button add-btn" data-id="${p.id}" type="button" ${productStock(p)?'':'disabled'}>افزودن</button></div></div></article>`).join(''):'<div class="empty">محصولی با این مشخصات پیدا نشد.</div>'}
function renderCart(){const count=cart.reduce((s,x)=>s+x.quantity,0);$('cart-count').textContent=fa(count);$('cart-total').textContent=money(cartTotal(cart));$('cart-items').innerHTML=cart.length?cart.map(i=>{const p=findProduct(i.productId);return p?`<div class="cart-row"><div class="cart-row-head"><div><b>${p.name}</b><br><small>${p.brand} | سایز ${fa(i.size)}</small></div><b>${money(p.price*i.quantity)}</b></div><div class="quantity"><button data-action="minus" data-key="${i.key}" type="button">−</button><span>${fa(i.quantity)}</span><button data-action="plus" data-key="${i.key}" type="button">+</button><button class="remove" data-action="remove" data-key="${i.key}" type="button">حذف</button></div></div>`:''}).join(''):'<div class="empty">سبد خرید شما خالی است.</div>'}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function openCart(){$('cart-drawer').classList.add('open');$('cart-drawer').setAttribute('aria-hidden','false');$('drawer-backdrop').classList.remove('hidden')}
function closeCart(){$('cart-drawer').classList.remove('open');$('cart-drawer').setAttribute('aria-hidden','true');$('drawer-backdrop').classList.add('hidden')}
function openProduct(id){const p=findProduct(id);$('product-detail').innerHTML=`<div class="detail-layout"><div class="detail-image">${p.emoji}</div><div><span class="product-brand">${p.brand}</span><h2>${p.name}</h2><p class="muted">${p.description}</p><b class="price">${money(p.price)}</b><p>سایز را انتخاب کنید:</p><div class="size-list">${Object.entries(p.stockBySize).map(([s,n])=>`<label><input type="radio" name="size" value="${s}"><span>${fa(Number(s))} <small>(${fa(n)})</small></span></label>`).join('')}</div><label>تعداد <input id="detail-quantity" class="quantity-input" type="number" min="1" value="1"></label><button class="primary-button" id="detail-add" type="button">افزودن به سبد</button></div></div>`;$('product-dialog').showModal();$('detail-add').onclick=()=>{const size=document.querySelector('input[name=size]:checked')?.value,q=Math.max(1,Number($('detail-quantity').value)||1),result=addToCart(cart,id,size,q);if(result.error){toast(result.error);return}saveCart();renderCart();$('product-dialog').close();toast('محصول به سبد خرید اضافه شد.')}}
function openCheckout(){if(!cart.length){toast('سبد خرید شما خالی است.');return}const total=cartTotal(cart);$('cash-amount').textContent=money(total);$('credit-amount').textContent=money(total/4)+' در هر قسط';$('installment-plan').innerHTML=installments(total).map((n,i)=>`<div><span>قسط ${fa(i+1)}</span><b>${money(n)}</b></div>`).join('');const credit=document.querySelector('input[name=payment][value=credit]').checked;$('installment-plan').classList.toggle('hidden',!credit);$('checkout-dialog').showModal()}
function init(){renderProducts();renderCart();$('search').oninput=renderProducts;$('brand-filter').onchange=renderProducts;$('sort-select').onchange=renderProducts;$('cart-button').onclick=openCart;$('close-cart').onclick=closeCart;$('drawer-backdrop').onclick=closeCart;$('checkout-button').onclick=openCheckout;$('close-checkout').onclick=()=>$('checkout-dialog').close();$('close-product').onclick=()=>$('product-dialog').close();$('confirm-order').onclick=()=>{const mode=document.querySelector('input[name=payment]:checked').value;toast(mode==='cash'?'سفارش نقدی شما ثبت نمایشی شد.':'درخواست خرید اعتباری شما ثبت نمایشی شد.');$('checkout-dialog').close();cart=[];saveCart();renderCart();closeCart()};document.querySelectorAll('input[name=payment]').forEach(x=>x.onchange=()=>$('installment-plan').classList.toggle('hidden',x.value!=='credit'||!x.checked));$('product-grid').onclick=e=>{const btn=e.target.closest('button');if(btn)openProduct(btn.dataset.id)};$('cart-items').onclick=e=>{const btn=e.target.closest('button');if(!btn)return;cart=btn.dataset.action==='remove'?cart.filter(x=>x.key!==btn.dataset.key):changeQuantity(cart,btn.dataset.key,btn.dataset.action==='plus'?1:-1);saveCart();renderCart()}}
if(typeof window!=='undefined')window.addEventListener('DOMContentLoaded',init);
if(typeof module!=='undefined')module.exports={PRODUCTS,productStock,addToCart,changeQuantity,cartTotal,installments};