import {products, addToCart, updateCartQuantity, cartTotals, cartQuantity} from './store.js';

const $ = selector => document.querySelector(selector);
let cart = JSON.parse(localStorage.getItem('tandpa-cart') || '[]');
let filters = JSON.parse(localStorage.getItem('tandpa-filters') || '{}');
let selectedProduct = null;
let modalSize = null;
let modalQuantity = 1;
let modalMethod = 'cash';
const fa = value => Number(value).toLocaleString('fa-IR');
const money = value => `${fa(value)} تومان`;
const saveCart = () => { localStorage.setItem('tandpa-cart', JSON.stringify(cart)); renderCart(); renderProducts(); };
const notify = message => { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(notify.timer); notify.timer = setTimeout(() => toast.classList.remove('show'), 2600); };

function filteredProducts() {
  const query = ($('#search').value || '').trim().toLowerCase();
  let list = products.filter(p => (!query || `${p.name} ${p.brand}`.toLowerCase().includes(query)) && (filters.brand === 'all' || !filters.brand || p.brand === filters.brand) && (filters.size === 'all' || !filters.size || p.sizes.includes(Number(filters.size))) && (filters.price === 'all' || !filters.price || (filters.price === 'under-3' ? p.price < 3000000 : filters.price === '3-5' ? p.price >= 3000000 && p.price <= 5000000 : p.price > 5000000)));
  const sort = filters.sort || 'popular';
  return list.sort((a,b) => sort === 'price-low' ? a.price-b.price : sort === 'price-high' ? b.price-a.price : sort === 'stock' ? b.stock-a.stock : b.popularity-a.popularity);
}
function renderProducts() {
  const list = filteredProducts(); $('#result-count').textContent = `${fa(list.length)} محصول`;
  $('#product-grid').innerHTML = list.length ? list.map(p => `<article class="product-card"><div class="product-image"><span class="brand-tag">${p.brand}</span><img src="${p.image}" alt="کفش ${p.name}"></div><div class="card-body"><h3>${p.name}</h3><p class="description">${p.description}</p><div class="price-row"><span class="price">${money(p.price)} <small>نقدی</small></span><span class="credit-label">۴ قسط بدون کارمزد</span></div><p class="stock ${p.stock < 5 ? 'low' : ''}">موجودی انبار: ${fa(p.stock)} جفت · سایزهای ${p.sizes.map(fa).join('، ')}</p><div class="card-actions"><button class="details-button" data-detail="${p.id}" type="button">جزئیات و خرید</button><button class="add-button" data-quick="${p.id}" type="button">افزودن</button></div></div></article>`).join('') : '<div class="empty-state">محصولی با این مشخصات پیدا نشد.<br>فیلترها را تغییر دهید.</div>';
}
function openModal(id) { selectedProduct = products.find(p => p.id === id); modalSize = selectedProduct.sizes.find(s => cartQuantity(cart,id,s) < selectedProduct.stock) || selectedProduct.sizes[0]; modalQuantity = 1; modalMethod = 'cash'; renderModal(); $('#modal').classList.remove('hidden'); }
function renderModal() { const p = selectedProduct; $('#modal-content').innerHTML = `<div class="detail-layout"><div class="detail-image"><img src="${p.image}" alt="کفش ${p.name}"></div><div><span class="eyebrow">${p.brand}</span><h2 id="modal-title">${p.name}</h2><p class="detail-copy">${p.description}. این محصول با طراحی ارگونومیک برای فعالیت‌های ورزشی روزمره ساخته شده است.</p><strong>سایز را انتخاب کنید</strong><div class="size-list">${p.sizes.map(s => `<button type="button" class="size-option ${modalSize===s?'selected':''}" data-size="${s}" ${cartQuantity(cart,p.id,s)>=p.stock?'disabled':''}>${fa(s)}</button>`).join('')}</div><strong>روش خرید</strong><div class="method-list"><button type="button" class="method-option ${modalMethod==='cash'?'selected':''}" data-method="cash">نقدی · ${money(p.price)}</button><button type="button" class="method-option ${modalMethod==='credit'?'selected':''}" data-method="credit">اعتباری · ۴ × ${money(p.installment)}</button></div><div class="quantity-control"><span>تعداد:</span><button type="button" data-modal-qty="minus">−</button><b>${fa(modalQuantity)}</b><button type="button" data-modal-qty="plus">+</button></div><button type="button" class="primary-button" id="modal-add">افزودن به سبد خرید</button></div></div>`; }
function renderCart() { const totals = cartTotals(cart); $('#cart-count').textContent = fa(totals.count); const box = $('#cart-items'); box.innerHTML = cart.length ? cart.map(item => { const p=products.find(x=>x.id===item.productId); return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>سایز ${fa(item.size)} · ${item.method==='credit'?'اعتباری':'نقدی'}</p><div class="cart-quantity"><button data-cart-action="minus" data-id="${p.id}" data-size="${item.size}">−</button><b>${fa(item.quantity)}</b><button data-cart-action="plus" data-id="${p.id}" data-size="${item.size}">+</button><button class="remove-button" data-cart-action="remove" data-id="${p.id}" data-size="${item.size}">حذف</button></div></div><span class="cart-price">${money((item.method==='credit'?p.installment:p.price)*item.quantity)}${item.method==='credit'?'<small> / قسط</small>':''}</span></div>`; }).join('') : '<div class="empty-state">سبد خرید شما خالی است.<br>محصول مورد علاقه‌تان را انتخاب کنید.</div>'; $('#cart-summary').innerHTML = cart.length ? `<div class="summary-line"><span>تعداد اقلام</span><b>${fa(totals.count)}</b></div><div class="summary-line total"><span>جمع ${cart.some(i=>i.method==='credit')?'پرداخت فعلی':'سبد'}</span><b>${money(totals.total)}</b></div>${cart.some(i=>i.method==='credit')?`<div class="credit-summary">مبلغ اقساط اعتباری: ${money(totals.installmentTotal)} در هر قسط · ۴ قسط مساوی</div>`:''}<button class="primary-button checkout" id="checkout">نهایی‌سازی نمایشی سفارش</button>` : ''; }
function persistFilters() { localStorage.setItem('tandpa-filters', JSON.stringify(filters)); }

$('#search').addEventListener('input', renderProducts);
['brand-filter','size-filter','price-filter','sort'].forEach(id => $( '#'+id).addEventListener('change', e => { filters[id.replace('-filter','').replace('sort','sort')] = e.target.value; persistFilters(); renderProducts(); }));
Object.entries(filters).forEach(([key,value]) => { const el = $('#'+(key==='brand'?'brand-filter':key==='size'?'size-filter':key==='price'?'price-filter':'sort')); if(el) el.value=value; });
$('#product-grid').addEventListener('click', e => { const detail=e.target.closest('[data-detail]'); const quick=e.target.closest('[data-quick]'); if(detail) openModal(detail.dataset.detail); if(quick) openModal(quick.dataset.quick); });
$('#modal').addEventListener('click', e => { if(e.target === $('#modal')) $('#modal').classList.add('hidden'); const size=e.target.closest('[data-size]'); if(size){modalSize=Number(size.dataset.size);renderModal();} const method=e.target.closest('[data-method]'); if(method){modalMethod=method.dataset.method;renderModal();} const q=e.target.closest('[data-modal-qty]'); if(q){ if(q.dataset.modalQty==='plus' && modalQuantity<selectedProduct.stock) modalQuantity++; if(q.dataset.modalQty==='minus' && modalQuantity>1) modalQuantity--; renderModal(); } if(e.target.id==='modal-add'){try{cart=addToCart(cart,selectedProduct,modalSize,modalQuantity,modalMethod);saveCart();$('#modal').classList.add('hidden');notify('محصول با موفقیت به سبد اضافه شد');}catch(err){notify(err.message);}} });
$('#modal-close').onclick=()=>$('#modal').classList.add('hidden');
$('#cart-button').onclick=()=>{$('#cart-drawer').classList.add('open');$('#cart-drawer').setAttribute('aria-hidden','false');$('#cart-button').setAttribute('aria-expanded','true');};
$('#drawer-close').onclick=()=>{$('#cart-drawer').classList.remove('open');$('#cart-drawer').setAttribute('aria-hidden','true');$('#cart-button').setAttribute('aria-expanded','false');};
$('#cart-items').addEventListener('click', e => { const action=e.target.closest('[data-cart-action]'); if(!action)return; const id=action.dataset.id,size=Number(action.dataset.size),item=cart.find(i=>i.productId===id&&i.size===size),p=products.find(x=>x.id===id); try { if(action.dataset.cartAction==='remove') cart=cart.filter(i=>!(i.productId===id&&i.size===size)); else cart=updateCartQuantity(cart,id,size,item.quantity+(action.dataset.cartAction==='plus'?1:-1),p.stock); saveCart(); notify(action.dataset.cartAction==='remove'?'محصول از سبد حذف شد':'سبد خرید به‌روزرسانی شد'); } catch(err){notify(err.message);} });
$('#cart-summary').addEventListener('click', e => { if(e.target.id==='checkout'){notify('سفارش شما با موفقیت ثبت نمایشی شد؛ پرداختی انجام نشد.');cart=[];saveCart();} });
renderProducts(); renderCart();
